# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75fc8613c28bdc5b359669fbe9d0bd34fc2d159ae9ee493dd9ddd0edce2789e0514f23690060c64fccfd593d3151b7a5855f4d50dec67e68392f36d7557798b0

test:
  secret_key_base: 8bb8dd113516a192dd7afaf9b9a1a773ec35d0539490cbaceccbca9c9206bd2573300d716aea2c07ed931740bbba543e05a6365c9bcc35362e916509ad5c9b69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
